version: 0.0
os: linux
files:
  - source: /dist
    destination: /var/www/html/cw/dist
  - source: /scripts
    destination: /var/www/html/cw/scripts
  - source: package.json
    destination: /var/www/html/cw
hooks:
 BeforeInstall:
 - location: scripts/beforeInstall.sh
   timeout: 300
   runas: root
 AfterInstall: 
 - location: scripts/afterInstall.sh
   timeout: 300
   runas: root
 ApplicationStart:
 - location: scripts/applicationStart.sh
   timeout: 300
   runas: root